### PR TITLE
Use the correct parameters for HttpClient::get and post

### LINKED ISSUE #287: [1.0] Request parameters not passed correctly to the HTTP client
I noticed something strange on the 1.0 branch: take a look at the arguments passed to the client in [AbstractProvider/getAccessToken](https://github.com/thephpleague/oauth2-client/blob/1.0/src/Provider/AbstractProvider.php#L275) and compare them to the function definition in [AbstractHttpAdapterTemplate](https://github.com/egeloen/ivory-http-adapter/blob/0.6.0/src/AbstractHttpAdapterTemplate.php#L50).

    $httpResponse = $client->post($this->urlAccessToken(), [
        'headers' => $this->getHeaders(),
        'body' => $requestParams,
    ]);

When I changed it locally to match the method header, everything worked as expected.

    $httpResponse = $client->post($this->urlAccessToken(), $this->getHeaders(), $requestParams);

### PR DESCRIPTION
**Pull request by shadowhand**
Fixes #287.

### CODE REVIEW

**Comment by ramsey** [comment]
Are you sure this is the correct way to pass these parameters in Guzzle 5? The documentation shows the method signature as that which you are replacing:

http://docs.guzzlephp.org/en/latest/http-messages.html#requests

**Comment by ramsey** [comment]
Doh! Nevermind. This is due to the Ivory adapter, and clearly I was only looking at the Guzzle documentation. :facepalm:

**Comment by rtheunissen** [comment]
Yup. https://github.com/guzzle/guzzle/blob/master/src/Client.php#L123

**Comment by rtheunissen** [comment]
Yup we were passing it as if we were passing it directly to Guzzle, rather than the ivory adapter. I think?

**Comment by shadowhand** [comment]
Exactly, we forgot to modify the `get` and `post` calls to match ivory syntax.

**Comment by shadowhand** [comment]
@ramsey updated.

**Comment by ramsey** [comment]
Thanks!

**Pull request merged**
