### PR TITLE
Remove newline in header since RFC 7230 deprecates multiline headers

### PR DESCRIPTION
**Pull request by ramsey**
See: https://tools.ietf.org/html/rfc7230#section-3.2.4

### CODE REVIEW

**Comment by ramsey** [comment]
@shadowhand, I wanted to kick this to you for review before merging it in, since you originally wrote this. I wanted to make sure I wasn't going to break the MAC authorization header.

**Comment by shadowhand** [comment]
> A field value might be preceded and/or followed by optional
   whitespace (OWS); a single SP preceding the field-value is preferred
   for consistent readability by humans.  The field value does not
   include any leading or trailing whitespace: OWS occurring before the
   first non-whitespace octet of the field value or after the last
   non-whitespace octet of the field value ought to be excluded by
   parsers when extracting the field value from a header field.

**Comment by shadowhand** [comment]
Seems like it should be replaced with a space.

**Comment by ramsey** [comment]
Good call. I added a space.

**Comment by shadowhand** [comment]
:+1:

**Pull request merged**
