### PR TITLE
Add current docs project to main project

### LINKED ISSUE #559: Move documentation site into master branch?
A [recent update by GitHub](https://github.com/blog/2233-publish-your-project-documentation-with-github-pages) allows you to configure project documentation publication to GitHub Pages from a sub-directory instead of the `gh-pages` branch. 

Is this something we are interested in doing with this project? It may reduce the need for two pull requests when adding providers to documentation.

### PR DESCRIPTION
**Pull request by stevenmaguire**
Moved a copy of the documentation site from `gh-pages` to `docs` directory. `docs` directory is included in `.gitattributes`.

After merging, the project's Github Pages settings should be updated to build from the `docs` directory in the master branch instead of `gh-pages` branch, according to [the blog post about the feature](https://github.com/blog/2233-publish-your-project-documentation-with-github-pages).

Resolves #559

### CODE REVIEW

**Comment by shadowhand** [comment]
Ping @reinink and @ramsey. This is above my pay grade.

**Comment by reinink** [comment]
I haven't actually switched any projects to the `/docs` folder yet, so I don't know what's involved. I'm assuming it just works? I wonder if it favors the docs folder, or the gh-pages branch? Worst case you revert these changes.

**Comment by stevenmaguire** [comment]
It's very straight forward.

demo

After you merge this, you visit [https://github.com/thephpleague/oauth2-client/settings](https://github.com/thephpleague/oauth2-client/settings) and toggle the Github Pages setting to build from `gh-pages` branch to `master/docs`. 

Worse case scenario, you merge, you try, it doesn't build, `gh-pages` is still intact you can revert and remove this directory :)

**Comment by ramsey** [comment]
Merging in and will change the settings. Let's see how this works.

**Comment by ramsey** [comment]
Change made. So far, it appears to be working.

**Comment by stevenmaguire** [comment]
ZOMG

**Comment by reinink** [comment]
Cool 😎

**Pull request merged**
