### PR TITLE
Add mention of PSR-7 to readme

### PR DESCRIPTION
**Pull request by SammyK**
Since the package is using the latest Guzzle release, it's all PSR-7y now. :)

### CODE REVIEW

**Comment by ramsey** [comment]
Is PSR-7 something that a package can be "compliant with?" It's not like it's a coding standard for us to adopt. Underlying packages may adhere to the PSR-7 interfaces, but I don't understand how that's important to this package.

**Comment by shadowhand** [comment]
Maybe "makes use of" would be more appropriate here. But I do think we should market the fact that the client works with PSR-7 interfaces, because it allows a lot more flexibility when creating APIs on top of the providers.

**Comment by SammyK** [comment]
> But I do think we should market the fact that the client works with PSR-7 interfaces, because it allows a lot more flexibility when creating APIs on top of the providers.

That was my thought. :)

**Comment by ramsey** [comment]
Okie dokie.

**Pull request merged**
