### PR TITLE
Added Slack to providers

### PR DESCRIPTION
**Pull request by adam-paterson**

### CODE REVIEW

**Comment by shadowhand** [comment]
Some of the type hinting is missing but generally seems to pretty good. I would recommend using the [auth.test](https://api.slack.com/methods/auth.test) endpoint to get user information, but it will require overloading more of AbstractProvider to make the additional call. :)

**Comment by adam-paterson** [comment]
@shadowhand, I did use `auth.test` originally but thought you'd recommend using a resource that actually returns some user information. I'll swap it out anyway and add the missing typehints.

**Comment by shadowhand** [comment]
@adam-paterson you would need to use `auth.test` and then `users.info` to fetch the resource owner details.

**Comment by adam-paterson** [comment]
@shadowhand still working on this, had other commitments at the moment.

**Comment by adam-paterson** [comment]
@shadowhand I've updated this now, can you check I've taken the right approach?

**Comment by shadowhand** [comment]
@adam-paterson looking better! I did notice one issue with the query strings, which I reported at adam-paterson/oauth2-slack#2 but otherwise the new implementation for fetching resource owner is great.

**Comment by adam-paterson** [comment]
@shadowhand thanks for that, fixed now.

**Pull request merged**
