### PR TITLE
Add oauth2-psn to README.PROVIDERS.md

### PR DESCRIPTION
**Pull request by hassankhan**
Added new PSN provider

### CODE REVIEW

**Comment by shadowhand** [comment]
I see nothing wrong here. I did a quick check and opened one issue about an unnecessary overload, but otherwise this looks very well implemented.

Don't forget to make a separate PR to add your provider to the list in the `gh-pages` branch!

**Comment by hassankhan** [comment]
Hi, thanks for the reply! I forgot to remove the `__construct()` method, I'll fix that in a new release shortly. I'll do the `gh-pages` PR after that :)

**Comment by hassankhan** [comment]
Pinging for an update

**Comment by shadowhand** [comment]
Thanks for checking in, merged now!

**Comment by hassankhan** [comment]
Thanks :)

**Pull request merged**
