### PR TITLE
Added AccessTokenInterface

### PR DESCRIPTION
**Pull request by lightningspirit**
Added AccessTokenInterface. Providers can now override AccessToken and add their own information.
This is really important since some idps providers other information and properties for the AccessToken.

### CODE REVIEW

**Comment by shadowhand** [comment]
I understand the intent of this change but am not sure this is best solution. A possibly better way to do this would be to create a `TokenFactory` that gets injected into each grant instance and then used like so:

```php
    public function handleResponse(array $response)
    {
        return $this->tokenFactory->create($response);
    }
```

**Comment by shadowhand** [comment]
After reviewing this again, I actually really like what you are suggesting, as it centralizes the token creation with provider while allowing the grant to modify it. I would keep the code you have, with one modification: change the interface name to `TokenInterface` for easier naming compatibility.

**Comment by shadowhand** [comment]
Also, this PR should be recreated against the master branch, as the 0.12.x branch is in maintenance mode.

**Comment by rtheunissen** [comment]
Why can't the provider just have it's own `AccessToken`, which simply extends `League\OAuth2\Client\Token\AccessToken`?

**Comment by ramsey** [comment]
Thank you so much for this, but I agree with @rtheunissen. Can providers just extend this, or is the interface needed?

**Comment by ajscarvalho** [comment]
It could be done by extension, but the point remains, it must receive an Access Token object 

I just think the signature, which was
handleResponse($reponse = [])
that was changed to 
handleResponse(AccessToken $token, array $response = null)
should be just:
handleResponse(AccessToken $token)

In fact, I don't even get why you should have the handleResponse if it's allways an Identity function. Are you previewing future developments where the handleResponse method will do more that it presently does?

**Comment by rtheunissen** [comment]
>  it must receive an Access Token object

Just to be clear that we're on the same page, if you extend `League\OAuth2\Client\Token\AccessToken`, that extension also qualifies as its parent type, ie. you can pass your extending class to that method as an `AccessToken`.

**Comment by lightningspirit** [comment]
Yes that is true. In facto we don't need that interface. I will refactor this proposal and attach a new one without the interface and simplifying all of these.

**Comment by rtheunissen** [comment]
Thanks @lightningspirit :)

**Comment by ramsey** [comment]
@lightningspirit, after you refactor, make sure you run `phpcs` before pushing your changes. The Travis build is failing on this pull request due to some coding standards violations. Refer to our [contributing guide](https://github.com/thephpleague/oauth2-client/blob/master/CONTRIBUTING.md) for instructions on what to run before pushing.

Thanks!

**Comment by ramsey** [comment]
@lightningspirit Any chance you can submit your changes/refactor by tomorrow? I will be cutting 1.0.0-alpha2 tomorrow (see #362).

**Comment by ramsey** [comment]
I am releasing 1.0.0-beta1 on Wednesday (15 July). At that point, I am freezing the API for 1.0, so that we can move forward with a stable 1.0.0 release soon. If you'd like this to be in 1.0, please submit your changes before Wednesday. Thanks!

**Comment by ramsey** [comment]
I released 1.0.0-beta1 last week, and I'm closing this since the 1.0 API is now frozen.

Please feel free to open a new pull request against the master branch, and we can work this into a future 1.1 or 1.2 release.

**Pull request closed without merging**
