### PR TITLE
Fix: sending JSON or multipart requests

### PR DESCRIPTION
**Pull request by fverry**
Sending url-encoded params, json or multipart requests with Guzzle is easy, because shortcuts are implemented within [`GuzzleHttp\Client::applyOptions()`](https://github.com/guzzle/guzzle/blob/7.5.0/src/Client.php#L340).

Currently, those shortcuts are unreachable through the League OAuth2 Client, and thus all its providers.

This fix relies on `AbstractProvider::getResponse()`, and does not affect `AbstractProvider::getAuthenticatedRequest()`.

[`GuzzleHttp\ClientInterface::send()`](https://github.com/guzzle/guzzle/blob/7.5.0/src/ClientInterface.php#L30) method supports a second optional `$options` parameter [since v6.0](https://github.com/guzzle/guzzle/commit/1a9ad6b55368283aaf73672a519e5177530991fb?diff=split#diff-7fe9d7bab1528c58fb39365621c6f02430dd01828c26fe8b00f0408de72c71b8).

Upgrading `AbstractProvider::getResponse()` to support this second optional parameter allows the developper to use a `"form_params"`, `"json"` or `"multipart"` option key :
```php
$options = ['multipart' => $multipart];
$request = $oauth2client->getAuthenticatedRequest($method, $url, $token);
$response = $oauth2client->getResponse($request, $options);
```
----
### See also
Fixes: #935 #985 
Duplicates: #967

----
### For immediate use

Run the following on composer CLI:
```sh
composer config repositories.oauth2-client vcs https://github.com/fverry/oauth2-client
composer require "league/oauth2-client:dev-httpclientinterface-send-options as 2.x-dev"
```

----
### Workaround

Use:
```php
$request = $oauth2client->getAuthenticatedRequest($method, $url, $token);
$oauth2client->getHttpClient()->send($request, $options);
```
Instead of:
```php
$request = $oauth2client->getAuthenticatedRequest($method, $url, $token, $options);
$oauth2client->getResponse($request);
```

### CODE REVIEW

**Comment by ramsey** [comment]
@fverry, thank you for submitting this PR. Please take a look at the failing tests and fix those. Then, we'll accept this.

**Comment by isleshocky77** [comment]
I'd note that this is an issue for `query` parameters as well as using `json`.  

@fverry I'm wondering why you chose this as the fix though. Would it not be better to fix [RequestFactory::getRequestWithOptions](https://github.com/thephpleague/oauth2-client/blob/master/src/Tool/RequestFactory.php#L75) to use [GuzzleHttp\Client::applyOptions()](https://github.com/guzzle/guzzle/blob/7.5.0/src/Client.php#L340) instead of cherry-picking only `headers`, `body`, and `version`?

**Comment by gavin310** [comment]
Wow thank god I found this thread because I was having a hell of a time getting POST requests to work. `$oauth2client->getHttpClient()->send($request, $options);` saved the day.

**Comment by ramsey** [comment]
Closing this in favor of focusing on https://github.com/thephpleague/oauth2-client/pull/1032 for the next major version of this library.

Thank you for contributing! 🎉

**Pull request closed without merging**
