### PR TITLE
Use expires to serialize access tokens

### PR DESCRIPTION
**Pull request by Daanvm**
This fixes issue #458.

### CODE REVIEW

**Comment by shadowhand** [comment]
Tests need to be updated.

**Comment by Daanvm** [comment]
I'm sorry, fixed it now.

**Comment by shadowhand** [comment]
In the future, I would recommend using `git commit --amend` instead of creating a second commit when working on a PR. I also recommend reading [this excellent post about commit messages](http://chris.beams.io/posts/git-commit/).

**Comment by Daanvm** [comment]
Thanks for the feedback. If you want I can update my first commit?

**Comment by shadowhand** [comment]
That would be good. :) I don't have merge privs, @ramsey will have to merge this when he is ready.

**Comment by ramsey** [comment]
All looks great. Merging.

**Comment by shadowhand** [comment]
@Daanvm nice work!

**Pull request merged**
