### PR TITLE
Add 3rdparty ESIA provider

### PR DESCRIPTION
**Pull request by garex**
ESIA is a russian national Unified authentication and authentication system for citizens, that allows access to verified citizen's data.
Coverage is 100%. Compatible and tested with PHP 5.6 and upper.
Uses `lcobucci/jwt` for parsing JWT inside access token and `ramsey/uuid` for generating state.

### CODE REVIEW

**Comment by ramsey** [comment]
@garex, I was looking through your library and noticed certificates and keys in the `resources/` folder. I don't know anything about the service, but I wanted to double-check on that, since it seems like a security risk to include your keys in the repository. Can you confirm that this is intentional?

Thanks!

**Comment by garex** [comment]
Its test keys. And other is public. So yes.

пт, 29 июня 2018 г., 4:01 Ben Ramsey <notifications@github.com>:

**Comment by garex** [comment]
@ramsey Any updates?

**Comment by ramsey** [comment]
Sorry for the delay. Thanks for the response. Merging in. Thanks!

**Pull request merged**
