### PR TITLE
Add php 8.3 to test matrix

### PR DESCRIPTION
**Pull request by flavioheleno**
This PR adds PHP 8.3 to the testing matrix.

### CODE REVIEW

**Comment by ruudk** [comment]
@ramsey I hope you have time to merge this 🙏  Especially since PHP 8.4 is around the corner and I'd like to add that to the matrix as well.

**Comment by ruudk** [comment]
@shadowhand Could you have a look here so we can prepare for PHP 8.4?

**Comment by stephanvierkant** [comment]
Let's drop support for End of Life versions as well. Only >=8.1 is supported right now. Support for 8.0 ended a year ago.

**Comment by ramsey** [comment]
> Let's drop support for End of Life versions as well.

I'm getting things ready for this. Stay tuned!

**Comment by ramsey** [comment]
Thank you for contributing! 🎉

**Pull request merged**
