### PR TITLE
Yahoo OAuth Provider is added

### PR DESCRIPTION
**Pull request by hayageek**
Ben,
I have added Yahoo OAuth Provider to the list.

### CODE REVIEW

**Comment by shadowhand** [comment]
@hayageek You should not include `@dev` in your `oauth2-client` requirement, as it will not work when users have `minimum-stability: stable` in their composer.json.

**Comment by shadowhand** [comment]
You might always want to consider using [The Rules](http://chris.beams.io/posts/git-commit/) as a guide to writing commit messages. :smile:

**Comment by hayageek** [comment]
shall i set "prefer-stable": true in composer.json ?

**Comment by shadowhand** [comment]
No, just remove the `@dev` from the `oauth2-client` requirement. You don't need it.

**Comment by hayageek** [comment]
Done. I have remove @dev from oauth2-client

**Comment by shadowhand** [comment]
Looks good! Thanks!

**Comment by ramsey** [comment]
Thanks, @hayageek!

**Comment by hayageek** [comment]
Ben,
can you update in the website also.
http://oauth2-client.thephpleague.com/providers/thirdparty/

**Comment by ramsey** [comment]
@hayageek I can try to get to that this weekend, but the code for the website is in the `gh-pages` branch of this repository. You're welcome to submit a pull request to that branch to update the page, if I don't get to it for a few days. Thanks!

**Pull request merged**
