### PR TITLE
Replace GuzzleHttp with PSR-18 HTTP Clients

### LINKED ISSUE #1019: Allow any psr-18 http client (instead of requiring guzzle)
```bash
composer why guzzlehttp/guzzle
league/oauth2-client 2.7.0 requires guzzlehttp/guzzle (^6.0 || ^7.0) 
```

I prefer to use the Symfony HttpClient, but this package requires guzzle.  Any chance it could be more generic, that is, require any PSR-18 client to operate, then the user can install guzzle or whatever they want.

Thanks for your consideration.  Not urgent, but it'd be nice to have one less dependency.

### PR DESCRIPTION
**Pull request by flavioheleno**
This pull request replaces the Guzzle HTTP Client with PSR 17 and 18 interfaces. Closes #1019.

#### Changes to Dependencies:

* The dependencies `psr/http-client`, `psr/http-factory`, and `psr/http-message` were added to the `require` section. 
* The `guzzlehttp/guzzle` package was moved to the `require-dev` section.

#### Changes to the AbstractProvider Class:

* Guzzle's `HttpClientInterface` was replaced with `ClientInterface` from the PSR-18 standard. 
* Guzzle's `RequestFactory` was replaced with `RequestFactoryInterface` and `StreamFactoryInterface` from the PSR-17 standard.

#### Removal of the RequestFactory Class:

* The entire `RequestFactory` class was removed as it's no longer needed with the introduction of the PSR-17 standard interfaces.

### CODE REVIEW

**Comment by verfriemelt-dot-org** [comment]
what needs to happen to move forward with this? :)

**Comment by verfriemelt-dot-org** [comment]
i tested this with my application and can confirm that everything is working as expected so far for me :+1:

**Comment by ramsey** [comment]
I'll review this while I'm on holiday, coming up in a couple of weeks, and will merge it then. It might require a new major version, which I'm happy to tag for this.

We have an interesting history with these kinds of requests, and I bet @shadowhand would agree with me that we are way overdue to accept this. 😁

I'm going to tag a bunch of issues and PRs from over the years here, just to connect things together:

- https://github.com/thephpleague/oauth2-client/issues/475
- https://github.com/thephpleague/oauth2-client/pull/538
- https://github.com/thephpleague/oauth2-client/issues/652
- https://github.com/thephpleague/oauth2-client/issues/685
- https://github.com/thephpleague/oauth2-client/issues/698
- https://github.com/thephpleague/oauth2-client/issues/704
- https://github.com/thephpleague/oauth2-client/issues/863
- https://github.com/thephpleague/oauth2-client/pull/885

**Comment by ramsey** [comment]
Don't worry about the test failures on PHP 7.1 and earlier. If I tag this for a new major version, I'll be dropping support for everything before PHP 8.1.

**Comment by flavioheleno** [comment]
I'll fix the unit tests errors running on 8.1+

**Comment by ramsey** [comment]
@flavioheleno FYI, I've created a `3.x` branch that targets PHP 8.1+, and I've repointed the based of this branch to `3.x` and resolved the conflicts in `composer.json`.

**Review by ramsey — APPROVED** [review]

**Pull request merged**
