### PR TITLE
Removing Eventbrite support and adding link in readme to new package

### PR DESCRIPTION
**Pull request by stevenmaguire**
As referenced in https://github.com/thephpleague/oauth2-client/issues/213, the Eventbrite support was in need of a new maintainer and support migrated to new package.

 Find a maintainer - me!
 Link in the README - in this PR
 Remove from league/oauth2-client - in this PR

### CODE REVIEW

**Comment by ramsey** [comment]
@philsturgeon, this should have been merged into the 1.0 branch, not master.

**Comment by stevenmaguire** [comment]
@ramsey & @philsturgeon I am doing a similar process with the microsoft package. Would you like me to submit the PR to merge into the 1.0 branch?

**Comment by ramsey** [comment]
Please send the PR to remove the providers to the 1.0 branch. They should not be removed from master at this time. I'll have to back this one out and reapply to the 1.0 branch when I get home. Thanks!

**Comment by stevenmaguire** [comment]
No problem. Sorry for this one. I did not realize that intention.

**Comment by ramsey** [comment]
Not a big deal. I blame @philsturgeon for merging it. :-)

**Comment by philsturgeon** [comment]
Oh f**k sorry. 

I'll just sit in the corner.

**Comment by philsturgeon** [comment]
I reverted it.

**Comment by stevenmaguire** [comment]
Would you like me to submit a new PR to remove Eventbrite from the 1.0 branch?

**Comment by philsturgeon** [comment]
Yeah please 

-- 
Phil

**Comment by stevenmaguire** [comment]
#245 is in!

**Pull request merged**
