### PR TITLE
Add toArray to ResourceOwnerInterface

### PR DESCRIPTION
**Pull request by shadowhand**
Provides a more consistent way to fetch whatever information is available about the resource owner, without assuming any particular structure.

### CODE REVIEW

**Comment by shadowhand** [comment]
I don't think this is unreasonable and it helps make the API consistent with other providers.

**Comment by ramsey** [comment]
I agree. This would help a dev in a recent conversation on an oauth2-facebook issue.

**Comment by stevenmaguire** [comment]
@ramsey since this change has updated the API, do you plan to cut a new beta release?

**Comment by ramsey** [comment]
Good question. I'm traveling today. I'll get a new beta release out in the morning.

**Pull request merged**
