### PR TITLE
Add Eve Online provider

### PR DESCRIPTION
**Pull request by okwinza**

### CODE REVIEW

**Comment by shadowhand** [comment]
I checked out the provider in question, it looks to be of high quality. :+1:

**Comment by okwinza** [comment]
Thanks @shadowhand ! 
I used official LinkedIn provider as a reference so it's mostly copy&paste :D 
Although code coverage looks strange to me because codebase is pretty much the same yet there is huge difference in % covered. 

Would appreciate any advice on this.

**Comment by stevenmaguire** [comment]
@okwinza that LinkedIn package _is_ pretty good, if I say so myself ;)

Your code coverage is so poor because your package includes an `example` directory, with what I assume to be code samples. That example directory is not excluded from the test suite and there are no tests for the code in that directory. If you exclude this directory from your test suite you will be in good shape on the code coverage front.

**Comment by okwinza** [comment]
@stevenmaguire thanks, got all 100 after excluding that dir.

**Comment by stevenmaguire** [comment]
:+1:

**Pull request merged**
