### PR TITLE
Update nest provider with replacement

### PR DESCRIPTION
**Pull request by stevenmaguire**
The existing google nest provider has zero tests, has not been updated in over a year, and as such it is not compatible with the latest version of the base package. I'd like to include a replacement.

### CODE REVIEW

**Comment by shadowhand** [comment]
Did you try contacting the current provider's author? I'm in favor of this if there is no other resolution.

**Comment by stevenmaguire** [comment]
I have emailed him asking for some input on the conversation.

**Comment by stevenmaguire** [comment]
@JC5 has responded via email and is ok with the change; he has even updated his project to point to the new one. https://github.com/JC5/nest-oauth2-provider

I've asked him to comment in here to ensure everything is cool.

**Comment by JC5** [comment]
Everything is cool, I've already updated my package to point to Steven's package.

**Comment by stevenmaguire** [comment]
If the docs migration to the master branch is going to stick, we can kill this PR. I've updated the other PR to include this change for the migrated docs project.

**Comment by stevenmaguire** [comment]
Is the `gh-pages` branch going to stick around?

**Comment by ramsey** [comment]
Nope. No need for it, now that we're using the `docs/` folder. I've removed the `gh-pages` branch.

**Comment by stevenmaguire** [comment]
Sweet!

**Pull request closed without merging**
