### PR TITLE
Add Drupal OAuth2-Server provider

### PR DESCRIPTION
**Pull request by chrishemmings**

### CODE REVIEW

**Comment by shadowhand** [comment]
Please also do another PR that updates the list in the gh-pages branch!

**Comment by shadowhand** [comment]
I opened a couple of issues for minor things that should be fixed, but overall this looks really good.

:+1:

**Comment by chrishemmings** [comment]
Cool beans,  I've opened a PR on gh-pages as requested.  I'll take a look at those issues now.

**Comment by chrishemmings** [comment]
Hey there,  I have addressed the issues you pointed out.  Thanks for the heads up :+1:

**Pull request merged**
