### PR TITLE
Replace RandomLib with native random functions

### PR DESCRIPTION
**Pull request by shadowhand**
RandomLib depends on mcrypt, which is deprecated in PHP 7.1. The new
random functions that are present in PHP 7 are more than sufficient for
our needs and a compat package is available for PHP 5.x.

Refs #574

### CODE REVIEW

**Comment by it-can** [comment]
I ran into this problem today with PHP7.1, can this be merged to the master branch (and also a tag)? Or is 2.0 coming anytime soon?

**Comment by HipsterJazzbo** [comment]
@shadowhand What's the status on this? I need to use this on 7.1, wondering what the path forward is.

**Comment by shadowhand** [comment]
@HipsterJazzbo @it-can see #602

**Comment by it-can** [comment]
@shadowhand any eta on v2?

**Comment by shadowhand** [comment]
Before the end of the week. Possibly even today.

**Comment by it-can** [comment]
very nice

**Pull request merged**
