### PR TITLE
[WIP] Working examples to illustrate use of the oauth2-client library

### PR DESCRIPTION
**Pull request by ramsey**
This pull request is a work-in-progress.

### CODE REVIEW

**Comment by shadowhand** [comment]
FWIW I have a demo repository up and running at [oauth2-demos][/shadowhand/oauth2-demos]). I'll try this out right now.

**Comment by ramsey** [comment]
Doh! I didn't mean to duplicate work. We don't need to include these.

**Comment by shadowhand** [comment]
@ramsey the content you have here is really fantastic though! If you can make a PR to merge what you've written up with my implementation, it would be a stellar combination of documentation and demonstration.

**Comment by shadowhand** [comment]
Also I am very much using a framework and the code might not be super easy to follow. I'm not really inclined to drop the framework, but perhaps explaining the calls like we do in the README is helpful?

**Comment by ramsey** [comment]
Closing this pull request. I'll either redirect it to fit into oauth2-demos or figure out a better place for the content to live.

**Pull request closed without merging**
