### PR TITLE
Add additional method for modifying token response

### PR DESCRIPTION
**Pull request by shadowhand**
Create `AbstractProvider::prepareAccessTokenResult` to allow providers to modify token responses. Particularly useful for mapping expirations and capturing any additional details that may come back with the token.

### CODE REVIEW

**Comment by shadowhand** [comment]
In some ways, it would be helpful if `AccessToken` simply took all additional fields passed in `$options` and stored them (perhaps a `$details = []` property?) for later usage.

**Comment by ramsey** [comment]
Thanks for the pull request!

Having a `$details` property on the AccessToken sounds like a good idea. In the 1.0 branch, though, I want to move away from public properties, so it might be a good idea to provider some accessor method to the `$details` property, rather than making it public.

**Comment by shadowhand** [comment]
@ramsey any idea when a new release will be tagged? This PR in particular is preventing our Square provider from being completely functional, because Square returns tokens with `expires_at` field, which we need to remap to `expires` to be recognized by the AccessToken class.

Thanks for the quick response!

**Comment by ramsey** [comment]
I've just tagged the 0.9.0 release. Enjoy!

**Comment by shadowhand** [comment]
Thanks Ben, that's great! Will update the Square provider asap.

**Pull request merged**
