### PR TITLE
update idpexception to account for empty strings

### PR DESCRIPTION
**Pull request by geofflancaster**
Some providers (ex. Google) specify an error response object which is an empty string in cases where a 403/401 are returned. This will force the exception to check that the value isset and it is not an empty string which will help prevent the Unknown error case from occurring.

### CODE REVIEW

**Comment by ramsey** [comment]
@geofflancaster Can you provide a test for this edge case? Thanks!

**Comment by ramsey** [comment]
Ping, @geofflancaster

**Comment by geofflancaster** [comment]
I'm here. Just swamped. I'll try to get to it tonight.

Thanks,
Geoff

**Comment by ramsey** [comment]
@geofflancaster, I'm ready to merge this in. I'd just like a test for it, please. :-)

**Comment by geofflancaster** [comment]
Test cases added.

**Comment by ramsey** [comment]
Looks like there might be conflicts. Can you merge master into your branch and see what break, please. :-)

**Comment by geofflancaster** [comment]
merge complete.

**Comment by ramsey** [comment]
Thanks, @geofflancaster.

That merge looked quite a bit hairy, and I'm not sure why the files listed as being in conflict were in conflict (for example, the README), since you didn't touch them in your branch. So, I pulled down your branch, backed out the merge, and then merged just your changes, resolving the conflict in IDPExceptionTest.

As a result, the following new commits were created in thephpleague/oauth2-client master branch:
* https://github.com/thephpleague/oauth2-client/commit/7faec8077fcf2d4d32ac5b1ea866846c624f0028
* https://github.com/thephpleague/oauth2-client/commit/847dbf5dfe295e4c981b7f7f39594b5b89647f72
* https://github.com/thephpleague/oauth2-client/commit/248f55c20149d972a112e572c612fb46a089d583
* https://github.com/thephpleague/oauth2-client/commit/da5e316c1beffd617cb8b4ec62623e3ab1144661
* https://github.com/thephpleague/oauth2-client/commit/54e404f911e149c8eb94fe3c6ff3f5b2acbdf382
* https://github.com/thephpleague/oauth2-client/commit/a91f3788cbdb492ca6ae47d5032ae25a124e0303

Thanks!

**Comment by geofflancaster** [comment]
Agree. I thought that was strange too. Thanks for taking care of it.

**Pull request closed without merging**
