### PR TITLE
Rename StandardProvider -> GenericProvider

### PR DESCRIPTION
**Pull request by shadowhand**
Also StandardResourceOwner -> GenericResourceOwner and fix tests.

Refs #179

### CODE REVIEW

**Comment by shadowhand** [comment]
cc @rtheunissen

**Comment by rtheunissen** [comment]
:sparkles:

**Comment by ramsey** [comment]
Please rebase. :-)

**Comment by shadowhand** [comment]
@ramsey should be good now.

**Comment by ramsey** [comment]
:+1:

**Pull request merged**
