### PR TITLE
Normalizing the style of comments

### PR DESCRIPTION
**Pull request by phelipealves**

### CODE REVIEW

**Comment by ramsey** [comment]
This doesn't just change comments. It also changes code. Did you manually make these changes, or did you use an automated tool to make them?

**Comment by phelipealves** [comment]
With the help of styleci.io. 
And checking line by line manually

**Comment by ramsey** [comment]
What style guide are you using that suggests removing the space around concatenation (`.`) operators?

**Comment by phelipealves** [comment]
Of according of [PHP Coding Standards Fixer]:(https://styleci.readme.io/v1.0/docs/fixers#concat_without_spaces)
- **concat_without_spaces** [symfony] Concatenation should be used
without spaces.

But if necessary I can go back to normal and change only the comments.

**Comment by ramsey** [comment]
I'm not familiar with StyleCI, but the general style we have been using fits with their `concat_with_spaces` directive.

**Comment by phelipealves** [comment]
The ok. I will return the commit and only send the changes in the comments.

**Comment by phelipealves** [comment]
these are the only problemas?

**Comment by ramsey** [comment]
Also, I want to be careful about your updates to the use of `@inheritdoc`. Please see earlier conversation here: https://github.com/thephpleague/oauth2-client/issues/351#issuecomment-113842281

This pull request represents a significant amount of changes, and while I do appreciate your eagerness to help and contribute to the project, we've been careful not to accept changes for the sake of change in the past. I'll need to take time to review all the changes before accepting them.

**Comment by phelipealves** [comment]
I believe it is best to ignore my changes and will analyze again and send only comments with project standards.

**Comment by ramsey** [comment]
Okay. We follow PSR-2 standards, but PSR-2 doesn't define spacing around the concatenation operator or spacing in comments, so that leads to a variety of different style tools formatting things differently. Sorry for the hassle. I do thank you for your contributions and I hope you'll contribute again! :-)

**Comment by phelipealves** [comment]
thank you

**Pull request closed without merging**
