### PR TITLE
If there is an error parsing a JSON response set the response as the error.

### PR DESCRIPTION
**Pull request by tenfef**
When connecting to a shitty API that returns a text error (or an HTML error)  even though we are expecting JSON, then we should escalate the text error otherwise all you get is "Unknown Error" which is super unhelpful.

### CODE REVIEW

**Comment by ramsey** [comment]
Please take a look at the 1.0 branch. I think this has already been corrected there.

**Comment by shadowhand** [comment]
It has indeed.

**Comment by shadowhand** [comment]
Further, this PR can't be done without a minor version bump, since it would change the API.

**Comment by tenfef** [comment]
Thanks for the fast response guys, will check out 1.0 (I was not aware of this branch)

**Comment by rtheunissen** [comment]
I'm working on a branch which is blocked by #315 which handles JSON a bit nicer. If #315 is accepted and merged, it would mean that we require PHP 5.5, and that we can use `json_last_error_msg`, which should help on top of what's already implemented on 1.0

**Pull request closed without merging**
