### PR TITLE
Added Resource Guru to provider site

### PR DESCRIPTION
**Pull request by adam-paterson**

### CODE REVIEW

**Comment by ramsey** [comment]
@adam-paterson, can you please rebase against the latest gh-pages branch and update this PR? Thanks!

**Comment by ramsey** [comment]
I'm not sure why you closed this. You can just force push on your branch to update a pull request, after you rebase.

**Comment by adam-paterson** [comment]
Whoops, it automatically closed it after I rebased. Best bet to roll back or issue a new PR against the rebased branch?

**Comment by ramsey** [comment]
Interesting. If it automatically closed, it's because what you pushed had no differences from the repo's gh-pages branch.

**Comment by adam-paterson** [comment]
@ramsey my mistake. Fixed now

**Pull request merged**
