### PR TITLE
Docblocked everything.

### PR DESCRIPTION
**Pull request by rtheunissen**
Would be good if someone could read through to double check everything.

Would be happy to do docs for all classes too, let me know.

### CODE REVIEW

**Comment by shadowhand** [comment]
Looks great. As a general suggestion, I recommend reading [git commit by Chris Beams](http://chris.beams.io/posts/git-commit/). In particular, the "imperative mood" rule really helped me.

**Comment by ramsey** [comment]
Since you mentioned the "imperative mood" rule in a previous comment somewhere, I've been following that in all my commits at work. I'll pass along the link to my team. Thanks!

**Comment by ramsey** [comment]
Looks great!

**Comment by rtheunissen** [comment]
@shadowhand Thanks for the info, was a good read. :+1:

**Pull request merged**
