### PR TITLE
Add support for PKCE (Proof Key for Code Exchange [RFC 7636])

### PR DESCRIPTION
**Pull request by rhertogh**
Support [RFC 7636](https://tools.ietf.org/html/rfc7636): Proof Key for Code Exchange. For more info please see https://oauth.net/2/pkce/

- [x] Code
- [x] Tests
- [x] Documentation

Fixes: #837

### CODE REVIEW

**Comment by D063520** [comment]
Hi, this is great! Could you provide some documentation too, then I would try it out ....

**Comment by rhertogh** [comment]
> Hi, this is great! Could you provide some documentation too, then I would try it out ....

To enable PKCE set the `pkceMethod` to `'S256'` or `'plain'` (Note: plain is **not** recommended)

```php
$provider = ClientTokenProvider([
    // ...
    'pkceMethod' => 'S256',
    // ...
);
```

**Comment by jcomack** [comment]
@rhertogh Am I correct in my assumption that this will _not_ work when using the `GenericProvider` and one will have to roll their own version that implements the `AbstractProvider`?

**Comment by rhertogh** [comment]
@jcomack 
> Am I correct in my assumption that this will _not_ work when using the `GenericProvider` and one will have to roll their own version that implements the `AbstractProvider`?

No, the example I gave was unclear (the ClientTokenProvider mentioned in the older version of the example was a custom class I used to extend from the GenericProvider). The example is updated.
So to be clear, you can use the `GenericProvider`.

**Comment by davidwindell** [comment]
This would be really helpful, thanks @rhertogh. Hopefully we'll see this merged soon :pray:

**Comment by rhertogh** [comment]
@shadowhand Could you approve running workflows on this PR to validate the tests.

**Comment by gdsmith** [comment]
Any movement on this? Looks like a good improvement, especially as [Oauth are saying PKCE is recommended for any Authorisation Code flow now](https://oauth.net/2/pkce/).

> PKCE was originally designed to protect the authorization code flow in mobile apps, but its ability to prevent authorization code injection makes it useful for every type of OAuth client, even web apps that use a client secret.

**Comment by websmurf** [comment]
What needs to be done in order for this pull request to be merged?
We're using the @rhertogh fork for some time now; but would like to be able to use the main package.

**Comment by gsirin** [comment]
@ramsey please merge this one!

**Comment by rhertogh** [comment]
@ramsey I've added tests for the missing code coverage parts (should be 100% now). Could you trigger a build to see the results?

**Review by ramsey — COMMENTED** [review]
This looks good to me. I've made a few suggestions.

**Comment by rhertogh** [comment]
@ramsey Suggestions have been committed.

**Comment by ramsey** [comment]
Thank you for contributing! 🎉

**Comment by websmurf** [comment]
Awesome work, thanks!

**Comment by gsirin** [comment]
Thank you!

**Comment by cdburgess** [comment]
When will this code show up in an official release? I see 2.6.1 is the latest that was released last December. Is there a better way to get this code to start working with PKCE requirements?

**Comment by ramsey** [comment]
I will try to tag a release in the next week.

**Comment by cdburgess** [comment]
Thanks!

**Comment by isaiahdahl** [comment]
@ramsey is this released yet? I see PKCE support in the [docs](https://oauth2-client.thephpleague.com/usage/) but it doesn't seem to have trace of that support in the installed package.

CleanShot 2022-10-11 at 12 44 03

**Comment by cdburgess** [comment]
I'm still waiting for it too. It hasn't been released yet. At least not in an actual version release.

**Comment by rhertogh** [comment]
@isaiahdahl, @cdburgess Until the new version is released you can use `"league/oauth2-client": "dev-master#43c59dd"` in your `composer.json` file. Just make sure to change it to the correct version when it is released.

**Comment by oddevan** [comment]
Great to see this! I'll update my [Twitter provider](https://github.com/smolblog/oauth2-twitter) with this once it's released.

**Comment by ChrisTitos** [comment]
Any update on releasing this feature?

**Comment by jakub-groncki** [comment]
Any chances of releasing this soon? Apparently it's a blocker for many developers.

**Comment by gsirin** [comment]
@ramsey please I need this one too

**Comment by skollro** [comment]
Waiting for the new release, too.

**Comment by carlituxman** [comment]
Waiting for the new release, too.

**Comment by geertw** [comment]
Still no release! I'm waiting too.

**Comment by rhertogh** [comment]
The new version is here 🎉 v2.7.0

**Pull request merged**
