### PR TITLE
Guzzle5

### PR DESCRIPTION
**Pull request by boulevard23**

### CODE REVIEW

**Comment by ramsey** [comment]
@boulevard23, your master branch seems pretty far behind our current master branch. Master is currently 1.0.0-dev, and we've just released 1.0.0-alpha1, which you might want to take a look at. This version uses Guzzle 6.0.

Thanks for your interest in the oauth2-client library.

**Comment by boulevard23** [comment]
Hi @ramsey, I created the PR by accident, I closed immediately. Sorry for the inconvenience.

**Comment by ramsey** [comment]
No worries. I figured it was an accident. I just wanted to make sure you were aware of the changes being made to master. :-)

**Comment by boulevard23** [comment]
Yea, the latest version is really exciting. Thanks for the heads up :)

**Pull request closed without merging**
