### PR TITLE
Allow approval_prompt to be set through options

### PR DESCRIPTION
**Pull request by jasonvarga**
Dropbox OAuth authorization URL fails if `approval_prompt` is in the query string. See screenshot:

image

This PR allows a provider to override it. This addresses #216 and is adapted from #40.
This allows you to do this in your provider:

``` php
public function getAuthorizationUrl($options = array())
{
  return parent::getAuthorizationUrl(array_merge([
    'approval_prompt' => []
  ], $options));
}
```

Setting the value to `[]` will cause it to be removed when `httpBuildQuery` is used in the parent.

I've created a Dropbox provider that I'll be moving into its own package. It was originally going to be part of this PR, but has since been removed, so you can see it in the commit history for this PR if you want.

If this gets the OK, I'll open a separate PR to link to my provider.

### CODE REVIEW

**Comment by ramsey** [comment]
Looks good. Thanks for the pull request!

**Comment by jasonvarga** [comment]
Does this need to be tagged before we can use this update?

**Comment by ramsey** [comment]
It does need to be tagged. I was considering some other issues before tagging it, though.

**Comment by jasonvarga** [comment]
Sure, no problem. Thanks for merging.

**Comment by ramsey** [comment]
I've just cut the 0.8.1 tag, which includes this fix. Thanks!

**Pull request merged**
